//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATDONGSAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BATDONGSAN()
        {
            this.CHITIETNHUCAUs = new HashSet<CHITIETNHUCAU>();
            this.HOPDONGs = new HashSet<HOPDONG>();
        }
    
        public string MaBDS { get; set; }
        public string TenBDS { get; set; }
        public string MaKH { get; set; }
        public string MaLoai { get; set; }
        public string MaTT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<long> DienTich { get; set; }
        public string GioiThieu { get; set; }
        public byte[] HinhAnh { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LOAIBD LOAIBD { get; set; }
        public virtual TINHTRANG TINHTRANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNHUCAU> CHITIETNHUCAUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONG> HOPDONGs { get; set; }
    }
}
