//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETNHUCAU
    {
        public string MaNC { get; set; }
        public string MaBDS { get; set; }
        public Nullable<long> DinhGia { get; set; }
        public string DieuKien { get; set; }
    
        public virtual BATDONGSAN BATDONGSAN { get; set; }
        public virtual NHUCAU NHUCAU { get; set; }
    }
}
