//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOPDONG()
        {
            this.PHIEUDENBUs = new HashSet<PHIEUDENBU>();
            this.THANHTOANs = new HashSet<THANHTOAN>();
        }
    
        public string MaHD { get; set; }
        public string MaNC { get; set; }
        public string MaBDS { get; set; }
        public string MaKH { get; set; }
        public string MaTK { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<System.DateTime> NgayThue { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
    
        public virtual BATDONGSAN BATDONGSAN { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHUCAU NHUCAU { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDENBU> PHIEUDENBUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANHTOAN> THANHTOANs { get; set; }
    }
}
