//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KINHDOANH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KINHDOANH()
        {
            this.THANHTOANs = new HashSet<THANHTOAN>();
            this.LOAITRANGTHAIs = new HashSet<LOAITRANGTHAI>();
        }
    
        public string MaKD { get; set; }
        public string MaTK { get; set; }
        public string MaLH { get; set; }
        public string MaLSP { get; set; }
        public string ChuDe { get; set; }
        public string DiaChi { get; set; }
        public Nullable<long> GiaBan { get; set; }
        public Nullable<long> GiaThue { get; set; }
        public Nullable<int> DT { get; set; }
        public Nullable<int> SoTang { get; set; }
        public Nullable<int> SoCan { get; set; }
        public Nullable<int> SoBlock { get; set; }
        public string GThieu { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual LOAIHINH LOAIHINH { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANHTOAN> THANHTOANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAITRANGTHAI> LOAITRANGTHAIs { get; set; }
    }
}
