//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDENBU
    {
        public string MaPhieu { get; set; }
        public string MaHD { get; set; }
        public string MaTK { get; set; }
        public string MaTT { get; set; }
        public Nullable<long> TongTien { get; set; }
    
        public virtual HOPDONG HOPDONG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual TINHTRANG TINHTRANG { get; set; }
    }
}
