//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUHEN
    {
        public string MaPH { get; set; }
        public Nullable<int> MaTN { get; set; }
        public string MaTK { get; set; }
        public string DIADIEM { get; set; }
        public Nullable<System.DateTime> NGAYGIO { get; set; }
    
        public virtual KHTN KHTN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
