//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class data_BDSEntities : DbContext
    {
        public data_BDSEntities()
            : base("name=data_BDSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BATDONGSAN> BATDONGSANs { get; set; }
        public virtual DbSet<CHITIETNHUCAU> CHITIETNHUCAUs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<HOPDONG> HOPDONGs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHTN> KHTNs { get; set; }
        public virtual DbSet<LOAIBD> LOAIBDS { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHUCAU> NHUCAUs { get; set; }
        public virtual DbSet<PHIEUHEN> PHIEUHENs { get; set; }
        public virtual DbSet<THANHTOAN> THANHTOANs { get; set; }
        public virtual DbSet<TINHTRANG> TINHTRANGs { get; set; }
    
        public virtual ObjectResult<string> P_MACV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("P_MACV");
        }
    
        public virtual ObjectResult<string> P_MAKH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("P_MAKH");
        }
    
        public virtual ObjectResult<string> P_MATK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("P_MATK");
        }
    
        public virtual ObjectResult<string> P_MaBDS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("P_MaBDS");
        }
    
        public virtual ObjectResult<string> P_MaHD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("P_MaHD");
        }
    
        public virtual ObjectResult<string> P_MaLoai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("P_MaLoai");
        }
    
        public virtual ObjectResult<string> P_MaNC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("P_MaNC");
        }
    
        public virtual ObjectResult<string> P_MaPhieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("P_MaPhieu");
        }
    
        public virtual ObjectResult<string> P_MaTT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("P_MaTT");
        }
    
        public virtual ObjectResult<string> P_MATToan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("P_MATToan");
        }
    
        public virtual ObjectResult<string> P_MAPH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("P_MAPH");
        }
    
        [DbFunction("data_BDSEntities", "F_THONGKETHANG")]
        public virtual IQueryable<F_THONGKETHANG_Result> F_THONGKETHANG(Nullable<System.DateTime> nGAYD, Nullable<System.DateTime> nGAYC)
        {
            var nGAYDParameter = nGAYD.HasValue ?
                new ObjectParameter("NGAYD", nGAYD) :
                new ObjectParameter("NGAYD", typeof(System.DateTime));
    
            var nGAYCParameter = nGAYC.HasValue ?
                new ObjectParameter("NGAYC", nGAYC) :
                new ObjectParameter("NGAYC", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_THONGKETHANG_Result>("[data_BDSEntities].[F_THONGKETHANG](@NGAYD, @NGAYC)", nGAYDParameter, nGAYCParameter);
        }
    }
}
